### ISSUE TITLE
Error installing pcsaft from PyPi

### ISSUE THREAD

**Issue by jAniceto** [zmeri/PC-SAFT#89]
Hi. 
First of all, thanks for the pcsaft package. 
I have been using it successfully for some time, always installing from PyPi without any issues.
However, for the last couple of months, I can't install using pip. I get the following error. 

```
pip install pcsaft

Collecting pcsaft
  Using cached pcsaft-1.1.0.tar.gz (96 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\José Aniceto\\AppData\\Local\\Temp\\pip-install-lsejtyns\\pcsaft_51108affc8d84edda8811d42c3d222c5\\setup.py'"'"'; __file__='"'"'C:\\Users\\José Aniceto\\AppData\\Local\\Temp\\pip-install-lsejtyns\\pcsaft_51108affc8d84edda8811d42c3d222c5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\José Aniceto\AppData\Local\Temp\pip-pip-egg-info-4w2j39ot'
         cwd: C:\Users\José Aniceto\AppData\Local\Temp\pip-install-lsejtyns\pcsaft_51108affc8d84edda8811d42c3d222c5\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\José Aniceto\AppData\Local\Temp\pip-install-lsejtyns\pcsaft_51108affc8d84edda8811d42c3d222c5\setup.py", line 16, in <module>
        with open("docs/README.rst", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'docs/README.rst'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/82/09/67965e2c19c5c2908b3350d042f68627ce7c2dcca461a9efcdb47a3a474c/pcsaft-1.1.0.tar.gz#sha256=9bf24a4be69a74b11e6fb35d587826a5bdf6b1e19f882071502a9c8cf363a019 (from https://pypi.org/simple/pcsaft/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pcsaft-1.0.1.tar.gz (80 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\José Aniceto\\AppData\\Local\\Temp\\pip-install-lsejtyns\\pcsaft_f7b6a077980e440eaacbb853b8da81d0\\setup.py'"'"'; __file__='"'"'C:\\Users\\José Aniceto\\AppData\\Local\\Temp\\pip-install-lsejtyns\\pcsaft_f7b6a077980e440eaacbb853b8da81d0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\José Aniceto\AppData\Local\Temp\pip-pip-egg-info-fwgfdzwo'
         cwd: C:\Users\José Aniceto\AppData\Local\Temp\pip-install-lsejtyns\pcsaft_f7b6a077980e440eaacbb853b8da81d0\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\José Aniceto\AppData\Local\Temp\pip-install-lsejtyns\pcsaft_f7b6a077980e440eaacbb853b8da81d0\setup.py", line 34, in <module>
        ext_modules=cythonize(ext_modules, language_level="3"))
      File "C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\lib\site-packages\Cython\Build\Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pcsaft.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9f/12/bf755fd10fa1451b436024a34e12c9977cd797fe05cd9c61d842f3157932/pcsaft-1.0.1.tar.gz#sha256=9e5c1ba1faeff88b90831eb783d94dadf3849368aab6449931654f7861438838 (from https://pypi.org/simple/pcsaft/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pcsaft-1.0.0.tar.gz (76 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\José Aniceto\\AppData\\Local\\Temp\\pip-install-lsejtyns\\pcsaft_4e793926df5041779a1ef3c3519eed76\\setup.py'"'"'; __file__='"'"'C:\\Users\\José Aniceto\\AppData\\Local\\Temp\\pip-install-lsejtyns\\pcsaft_4e793926df5041779a1ef3c3519eed76\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\José Aniceto\AppData\Local\Temp\pip-pip-egg-info-qt24xzvb'
         cwd: C:\Users\José Aniceto\AppData\Local\Temp\pip-install-lsejtyns\pcsaft_4e793926df5041779a1ef3c3519eed76\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\José Aniceto\AppData\Local\Temp\pip-install-lsejtyns\pcsaft_4e793926df5041779a1ef3c3519eed76\setup.py", line 34, in <module>
        ext_modules=cythonize(ext_modules, language_level="3"))
      File "C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\lib\site-packages\Cython\Build\Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "C:\Users\José Aniceto\.virtualenvs\egichem-lv3jR6we\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pcsaft.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/18/0c/a24535490e508e07185a7b19d532185dee8c9703a4b2dc057f57617a30dc/pcsaft-1.0.0.tar.gz#sha256=fce512b121506fb842b05029146a7fab7797130bea320c16fb2788500835a2b0 (from https://pypi.org/simple/pcsaft/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pcsaft (from versions: 1.0.0, 1.0.1, 1.1.0)
ERROR: No matching distribution found for pcsaft
```

Is this something fixable?

**Comment by zmeri** [comment]
Hi,
I'm glad the package has been helpful. Could you tell me what system you're
trying to install on?

**Comment by jAniceto** [comment]
I'm on Windows 10 and Python 3.9.

**Comment by zmeri** [comment]
Ok, let me take a look at it.

**Comment by zmeri** [comment]
Ok, I now setup continuous integration so that binaries are built for a wide range of operating systems and Python 3 versions. The new version with all the binaries is 1.2.1, so check to make sure you are getting the right version if you are getting an error. Try installing now and let me know how it goes.

**Comment by jAniceto** [comment]
Hi. Just tested and seems to be working correctly. Thanks.
